<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidRepository extends EntityRepository
{
    public function findMyBid($user,$stage=null,$searchParam=null,$limit=null)
    {

        $query = $this ->createQueryBuilder('l')
            ->select('p')
            ->from('AppBundle:Bid','p')
            ->where('p.member = :member')
            ->setParameter('member', $user);

        if(!$stage == null){
            //convert to lowercase because all the state is stored in the lowercase in the database
            $transformedStage=strtolower($stage);
            $query =  $query->andWhere('p.stage = :stage')
                ->setParameter('stage', $transformedStage);

        }


        if(!$searchParam == null){

            $cleanedParam  = '%'.trim($searchParam).'%';

            $query = $query->andWhere('p.name LIKE :name')
                ->orWhere('p.id LIKE :id')
                ->setParameter('name',$cleanedParam)
                ->setParameter('id',$cleanedParam);

        }



        if(!$limit == null){
            $query = $query->setMaxResults($limit);
        }

        $query->orderBy('p.created', 'DESC');
        $query = $query ->getQuery()->getResult();

        return $query;
    }



/*todo: you can never have more than one active bid for one project. enforce this
*/
    public function getMyProjectBid($member,$project) {
        return $this
            ->createQueryBuilder('e')
            ->select('e')
            ->where('e.member = :member')
            ->andWhere('e.project = :project')
            ->setParameter('member',$member)
            ->setParameter('project', $project)
            ->orderBy('e.id', 'DESC')
         //   ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
