<?php

namespace AppBundle\Repository;

/**
 * BidSubscriptionFundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BidSubscriptionFundRepository extends \Doctrine\ORM\EntityRepository
{
}
