<?php

namespace AppBundle\Repository;

/**
 * ChukoloBankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChukoloBankRepository extends \Doctrine\ORM\EntityRepository
{
}
