<?php

namespace AppBundle\Repository;

/**
 * ChukoloFundLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChukoloFundLogRepository extends \Doctrine\ORM\EntityRepository
{
}
