<?php

namespace AppBundle\Repository;

/**
 * ContractInvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractInvoiceRepository extends \Doctrine\ORM\EntityRepository
{

    public function findContractInvoice($bid) {
        return $this
            ->createQueryBuilder('e')
            ->select('e')
            ->where('e.contract = :bid')
            ->setParameter('bid',$bid)
            ->getQuery()
            ->getSingleResult();
    }
}
