<?php

namespace AppBundle\Repository;

/**
 * DeliverableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliverableRepository extends \Doctrine\ORM\EntityRepository
{
}
