<?php

namespace AppBundle\Repository;

/**
 * FundLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FundLogRepository extends \Doctrine\ORM\EntityRepository
{
}
