<?php

namespace AppBundle\Repository;

/**
 * FundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FundRepository extends \Doctrine\ORM\EntityRepository
{
}
