<?php

namespace AppBundle\Repository;

/**
 * MemberBankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberBankRepository extends \Doctrine\ORM\EntityRepository
{
}
