<?php

namespace AppBundle\Repository;

/**
 * MembershipFundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembershipFundRepository extends \Doctrine\ORM\EntityRepository
{
}
