<?php

namespace AppBundle\Repository;

/**
 * MilestoneProposalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilestoneProposalsRepository extends \Doctrine\ORM\EntityRepository
{
}
