<?php

namespace AppBundle\Repository;

/**
 * ProjectSubscriptionFundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectSubscriptionFundRepository extends \Doctrine\ORM\EntityRepository
{
}
