<?php

namespace AppBundle\Repository;

/**
 * ProjectClauseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectClauseRepository extends \Doctrine\ORM\EntityRepository

{
    //fixed is a type of project. the idea is that for each project type get the general +project type clause
    public function findFixedClause()
    {
        return $this
            ->createQueryBuilder('l')
            ->select('c')
            ->from('AppBundle:ProjectClause','c')
            ->where('c.projectType=:fixed AND c.isGeneral=:true AND c.enabled=:true')
            ->setParameter('fixed', "fixed")
            ->setParameter('true', true)
            ->getQuery()
            ->getResult();

    }
}
