<?php

namespace AppBundle\Repository;

/**
 * ProjectCommissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectCommissionRepository extends \Doctrine\ORM\EntityRepository
{
}
