<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends EntityRepository
{
    public function findCategorySkill($category)
    {
        return $this
            ->createQueryBuilder('l')
            ->select('p')
            ->from('AppBundle:Skill','p')
            ->join('p.category', 'c')
            ->where('c = :category')
            ->setParameter('category', $category)
            ->getQuery()
            ->getResult();
    }

}
