<?php

namespace AppBundle\Repository;

/**
 * SponsorshipFundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorshipFundRepository extends \Doctrine\ORM\EntityRepository
{
}
