<?php

namespace AppBundle\Repository;

/**
 * VerifyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VerifyRepository extends \Doctrine\ORM\EntityRepository
{
}
