<?php

namespace AppBundle\Repository;

/**
 * WithdrawalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WithdrawalRepository extends \Doctrine\ORM\EntityRepository
{
}
