<?php

namespace AppBundle\Repository;

/**
 * XPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class XPRepository extends \Doctrine\ORM\EntityRepository
{
}
