app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

settings:
    resource: "@DmishhSettingsBundle/Resources/config/routing.yml"
    prefix: /settings